"""policy documents, chunks, rules

Revision ID: 07d8b779de6e
Revises: dbf14c43de00
Create Date: 2026-06-05 17:17:57.976016+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "07d8b779de6e"
down_revision: str | None = "dbf14c43de00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor_documents",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "chunked",
                "compiled",
                "failed",
                name="documentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vendor_documents_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_documents_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_documents")),
    )
    op.create_index(
        op.f("ix_vendor_documents_organization_id"),
        "vendor_documents",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_documents_vendor_id"), "vendor_documents", ["vendor_id"], unique=False
    )
    op.create_table(
        "policy_chunks",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["vendor_documents.id"],
            name=op.f("fk_policy_chunks_document_id_vendor_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_policy_chunks_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_chunks")),
    )
    op.create_index(
        op.f("ix_policy_chunks_document_id"), "policy_chunks", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_policy_chunks_vendor_id"), "policy_chunks", ["vendor_id"], unique=False
    )
    op.create_table(
        "policy_rules",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column(
            "rule_type",
            sa.Enum(
                "max_invoice_amount",
                "require_field",
                "allowed_payment_terms",
                "line_item_price_cap",
                "requires_purchase_order",
                "currency",
                "custom",
                name="policyruletype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_quote", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "approved",
                "rejected",
                name="policyrulestatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["vendor_documents.id"],
            name=op.f("fk_policy_rules_document_id_vendor_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_policy_rules_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_policy_rules_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_rules")),
    )
    op.create_index(
        op.f("ix_policy_rules_organization_id"), "policy_rules", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_policy_rules_vendor_id"), "policy_rules", ["vendor_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policy_rules_vendor_id"), table_name="policy_rules")
    op.drop_index(op.f("ix_policy_rules_organization_id"), table_name="policy_rules")
    op.drop_table("policy_rules")
    op.drop_index(op.f("ix_policy_chunks_vendor_id"), table_name="policy_chunks")
    op.drop_index(op.f("ix_policy_chunks_document_id"), table_name="policy_chunks")
    op.drop_table("policy_chunks")
    op.drop_index(op.f("ix_vendor_documents_vendor_id"), table_name="vendor_documents")
    op.drop_index(op.f("ix_vendor_documents_organization_id"), table_name="vendor_documents")
    op.drop_table("vendor_documents")
    # ### end Alembic commands ###
