#!/usr/bin/env bash
# One-command local setup for AP Invoice Intelligence.
#
#   ./scripts/setup.sh                 # full setup (uv, deps, .env, Postgres, migrations)
#   ./scripts/setup.sh --seed          # also create a demo org + API key
#   ./scripts/setup.sh --verify        # also run the full test suite (unit + integration)
#   ./scripts/setup.sh --demo          # also run the live end-to-end demo
#   ./scripts/setup.sh --all           # setup + seed + verify + demo (recommended first run)
#   ./scripts/setup.sh --no-start      # set up but don't start Postgres
#
# Idempotent: safe to re-run. Never overwrites an existing .env.
set -euo pipefail

# --- locate repo root (this script lives in scripts/) ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

SEED=false
VERIFY=false
DEMO=false
START_DB=true
for arg in "$@"; do
    case "$arg" in
        --seed) SEED=true ;;
        --verify) VERIFY=true ;;
        --demo) DEMO=true; SEED=true ;;
        --all) SEED=true; VERIFY=true; DEMO=true ;;
        --no-start) START_DB=false ;;
        -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "Unknown option: $arg" >&2; exit 1 ;;
    esac
done

# The shell may pre-set VIRTUAL_ENV to a path uv should ignore.
unset VIRTUAL_ENV || true

say()  { printf '\n\033[1;36m==>\033[0m \033[1m%s\033[0m\n' "$1"; }
ok()   { printf '    \033[32m✓\033[0m %s\n' "$1"; }
warn() { printf '    \033[33m!\033[0m %s\n' "$1"; }
die()  { printf '\n\033[31m✗ %s\033[0m\n' "$1" >&2; exit 1; }

# --- 1. prerequisites -------------------------------------------------------
say "Checking prerequisites"
command -v docker >/dev/null 2>&1 || die "Docker is required. Install Docker and retry."
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required (got none)."
command -v curl >/dev/null 2>&1 || die "curl is required."
ok "Docker + Compose + curl found"

# --- 2. uv (Python toolchain) ----------------------------------------------
if ! command -v uv >/dev/null 2>&1; then
    say "Installing uv (Python package manager)"
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi
export PATH="$HOME/.local/bin:$PATH"
command -v uv >/dev/null 2>&1 || die "uv install failed; add ~/.local/bin to PATH and retry."
ok "uv $(uv --version | awk '{print $2}')"

# --- 3. dependencies --------------------------------------------------------
say "Installing dependencies (uv sync)"
uv sync --extra dev
ok "Virtualenv ready at .venv"

# --- 4. .env (generate secrets once) ---------------------------------------
if [ -f .env ]; then
    say ".env already exists — leaving it untouched"
else
    say "Creating .env with generated secrets"
    PEPPER="$(uv run python -c 'import secrets; print(secrets.token_urlsafe(48))')"
    ADMIN="$(uv run python -c 'import secrets; print(secrets.token_urlsafe(32))')"
    cat > .env <<EOF
# Generated by scripts/setup.sh — local development only. Do not commit.
AP_ENVIRONMENT=development
AP_LOG_JSON=false
AP_DATABASE_URL=postgresql+asyncpg://ap:ap_password@localhost:5432/ap_invoice
AP_API_KEY_PEPPER=${PEPPER}
AP_ADMIN_TOKEN=${ADMIN}
# LLM provider (mandatory) — handles extraction (vision) + decision. claude | openai.
AP_LLM_PROVIDER=claude
AP_ANTHROPIC_API_KEY=${AP_ANTHROPIC_API_KEY:-}
# For GPT instead: set AP_LLM_PROVIDER=openai and AP_OPENAI_API_KEY=...

# Used by docker compose for the Postgres container.
POSTGRES_USER=ap
POSTGRES_PASSWORD=ap_password
POSTGRES_DB=ap_invoice
EOF
    ok "Wrote .env (admin token + key pepper generated)"
fi

if [ "$START_DB" = false ]; then
    say "Skipping database start (--no-start). Run 'make db-up && make migrate' when ready."
    exit 0
fi

# --- 5. PostgreSQL ----------------------------------------------------------
say "Starting PostgreSQL (docker compose)"
docker compose up -d postgres
printf '    waiting for Postgres'
for _ in $(seq 1 30); do
    if docker compose exec -T postgres pg_isready -U ap -d ap_invoice >/dev/null 2>&1; then
        printf '\n'; ok "Postgres is ready"; break
    fi
    printf '.'; sleep 1
done
docker compose exec -T postgres pg_isready -U ap -d ap_invoice >/dev/null 2>&1 \
    || die "Postgres did not become ready in time."

# Create the dedicated test database (best effort; ignored if it exists).
docker compose exec -T postgres createdb -U ap ap_invoice_test >/dev/null 2>&1 \
    && ok "Created test database 'ap_invoice_test'" \
    || ok "Test database already present"

# --- 6. migrations ----------------------------------------------------------
say "Applying database migrations"
uv run alembic upgrade head
ok "Schema is up to date"

# --- 7. optional demo seed --------------------------------------------------
if [ "$SEED" = true ]; then
    say "Seeding a demo organization, API key, and vendor"
    uv run python scripts/seed.py
fi

# --- 8. optional: run the test suite ----------------------------------------
if [ "$VERIFY" = true ]; then
    say "Running the full test suite (unit + integration)"
    uv run pytest -q
    ok "All tests passed"
fi

# --- 9. optional: live end-to-end demo --------------------------------------
if [ "$DEMO" = true ]; then
    say "Running the live end-to-end demo (starting the API briefly)"
    uv run uvicorn ap_invoice.api.main:app --host 127.0.0.1 --port 8000 \
        >/tmp/ap_demo_api.log 2>&1 &
    DEMO_API_PID=$!
    # shellcheck disable=SC2064
    trap "kill ${DEMO_API_PID} 2>/dev/null || true" EXIT
    printf '    waiting for the API'
    for _ in $(seq 1 30); do
        if curl -fs -o /dev/null http://127.0.0.1:8000/health/ready 2>/dev/null; then
            printf '\n'; break
        fi
        printf '.'; sleep 1
    done
    curl -fs -o /dev/null http://127.0.0.1:8000/health/ready 2>/dev/null \
        || die "API did not start (see /tmp/ap_demo_api.log)."
    uv run python scripts/demo.py
    kill "${DEMO_API_PID}" 2>/dev/null || true
    trap - EXIT
fi

# --- done -------------------------------------------------------------------
say "Setup complete 🎉"
cat <<'EOF'
Run the services (each in its own shell):
  make run-api     # REST API  → http://127.0.0.1:8000/docs
  make run-mcp     # MCP server → http://127.0.0.1:8080/mcp

Handy commands:
  make seed        # create a demo org + API key (prints the key)
  make demo        # live end-to-end walkthrough (needs the API running)
  make test        # unit tests        |   make test-int   # integration tests

Connect a Claude client (with the MCP server running and an org key):
  claude mcp add --transport http ap-invoice http://localhost:8080/mcp \
    --header "Authorization: Bearer <your-org-api-key>"
  # full guide: docs/local-testing.md

The LLM is mandatory (extraction + decision). Set the provider in .env:
  AP_LLM_PROVIDER=claude   AP_ANTHROPIC_API_KEY=sk-ant-...   # or
  AP_LLM_PROVIDER=openai   AP_OPENAI_API_KEY=sk-...

Your admin token and API-key pepper are in .env.
EOF
